### ISSUE TITLE
Doesn't seem to work with RubyMine7.0.4

### ISSUE THREAD

**Issue by davelaflam** [idok/coffee-lint-plugin#1]
Update: 
RubyMine version 7.1.4
It appears that the coffeelint plugin works within certain directories but not all.
For example, the plugin will work great within my repoName/spec/javascripts test directory. However, it appears the plugin will not work within the Rails asset pipeline when working on javascript files within the repoName/app/assets/javascripts directory.
I can't tell if this is an issue with the coffeelint plugin, RubyMine editor or the Rails asset pipeline. 
Any help would be greatly appreciated.

**Comment by nedden** [comment]
+1

**Comment by stereodenis** [comment]
+1

**Comment by xxx** [comment]
+1. Still a problem on 8.x (running 8.0.3 at the moment).

**Comment by idok** [comment]
Please provide more information on the issue, maybe a sample project or instructions how to reproduce.

**Comment by jekuno** [comment]
+1

More details: I have a project with a base directory `projectbase` which contains the config file `coffeelint.json`.

Linting does not work for a js file located below the app/assets directory e.g. `/projectbase/app/assets/javascripts/models/mymodel.js.coffee` or `/projectbase/app/assets/mymodel.js.coffee`

However linting works when I move the js file to any different location e.g. `/projectbase/app/mymodel.js.coffee`, `/projectbase/mymodel.js.coffee` or `/projectbase/spec/javascripts/mymodel.js.coffee`.

I suppose this is related to some special handling of the assets directory by RubyMine because linting works when I open the subdirectory `/projectbase/app/assets/javascripts` as a separate (non Rails) project in RubyMine.

**Comment by xxx** [comment]
Hi,

Sorry for taking so long to get back, but I have a demo project up at https://github.com/xxx/rubymine-coffeelint-test that demonstrates this problem.

**Comment by idok** [comment]
Thanks for the effort, I have managed to reproduce the issue, but unable to solve it.
It seems that Rubymine is not triggering the annotator for that folders, I'm having problems checking it further as I don't have a license for Rubymine and my evaluation period is over :(
If anyone wants to check it further / open an issue to jetbrains / submit a PR - it will be great.

**Comment by xxx** [comment]
@idok It looks like I'm going to get some time to work on this over the next week or two, but I'm not sure where to start. It's not clear how I could set up a harness to see what hooks into where and/or debug the plugin without having to package it up and uninstall/reinstall every time.

Do you have any pointers on that front?

**Comment by idok** [comment]
I have posted a question here:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206531349-External-annotator-does-not-work-on-certain-folders-in-rubymine

I think we need some help from Jetbrains here.

**Comment by idok** [comment]
This is an open issue, please vote for it:
 https://youtrack.jetbrains.com/issue/RUBY-17915

**Comment by davelaflam** [comment]
closing this issue as it has gone on for way to long. Plugin and App are not wroth using any longer.
